name: pre-commit

on:
  push:
    branches-ignore:
      - 'wip/**'
  pull_request:
    branches:
      - 'main'
  # manually run the workflow from the Actions tab
  workflow_dispatch:

concurrency:
  # Cancel previous actions from the same PR or branch except 'main' branch.
  # For more info, see:
  # https://docs.github.com/en/actions/using-jobs/using-concurrency
  # https://docs.github.com/en/actions/learn-github-actions/contexts
  group: >
    concurrency-group::${{ github.workflow }}::
    ${{ github.event.pull_request.number > 0
        && format('pr-{0}', github.event.pull_request.number)
        || github.ref_name
    }}${{
      github.ref_name == 'main'
      && format('::{0}', github.run_id)
      || ''
    }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
      with:
        python-version: '3.13'
    - uses: asdf-vm/actions/install@1902764435ca0dd2f3388eea723a4f92a4eb8302  # 4.0.0
      with:
        tool_versions: |
          action-validator 0.6.0
          hadolint 2.12.0
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # v3.0.1
